### ISSUE TITLE
Multiplying x 2 the shipping cost when the order is sent to Paypal.

### ISSUE THREAD

**Issue by powerblue** [academe/wc-multiple-packages#20]
I have Packages Configuration for WooCommerce plugin installed and it is working perfectly except for it is multiplying x 2 the shipping cost when the order is sent to Paypal using Woocommerce's standard Paypal feature.

Is there any way that this can be fixed? 

![screen shot 2016-07-02 at 8 34 54 pm](https://cloud.githubusercontent.com/assets/7293714/16542943/888c80e0-4093-11e6-8443-3af130117d5f.png)
![screen shot 2016-07-02 at 8 35 19 pm](https://cloud.githubusercontent.com/assets/7293714/16542946/8d439cae-4093-11e6-9dd9-ca94ab4f02f8.png)

**Comment by judgej** [comment]
Could you give me the versions of the plugins you are using (WP, WC, PayPal plugin).

**Comment by powerblue** [comment]
Hi,

Word Press: 4.5.3
WooCommerce: 2.6.1
WooCommerce PayPal: default PayPal with Enable PayPal standard set to ON.

Thanks

**Comment by powerblue** [comment]
Can I pay to have the fix implemented more quickly?

**Comment by judgej** [comment]
Can you provide some more details? What is showing as double what it should be, and where? What do you have set up to make this happen?

**Comment by powerblue** [comment]
I just have Woocommerce with the default PayPal set to "enable 
standard", and the Packages Configuration for WooCommerce enabled and 
set to use a custom field  "_vendor" to split the products into 
packages, and when an order is being placed, the order total page is 
working perfectly, however, when the customer clicks "Proceed to PayPal" 
on the PayPal page on the left where the order is itemized, the shipping 
cost is always doubled.

Thanks

Whenever there is an order, no matter the amount of the

**Comment by judgej** [comment]
I'm not seeing that. I am seeing the postage breakdown being the sum of all the postage rates for the packages, which is what I would expect. So if there are two packages, both with a postage of £10, then the total postage will be £20.

The grand total in PP is showing as the same as the grand total in WC.

**Comment by powerblue** [comment]
In the order in the attached screenshots it shows the total shipping 
cost of 17.60 being doubled to 35.20.

Thanks

**Comment by judgej** [comment]
I've not seen any screen shots. Could you attach them to an issue comment?

**Comment by powerblue** [comment]
Sure.

![screen shot 2016-07-02 at 8 34 54 pm](https://cloud.githubusercontent.com/assets/7293714/16542951/b5bae322-4093-11e6-81f8-a565ebe1f0db.png)
![screen shot 2016-07-02 at 8 35 19 pm](https://cloud.githubusercontent.com/assets/7293714/16542952/bc8b4ac0-4093-11e6-92b8-f82d33e7a107.png)

**Comment by powerblue** [comment]
I've uploaded the screen shots to a GitHub comment.

Thanks

**Comment by judgej** [comment]
How bizarre! So we can start narrowing it down, does this _only_ have with PayPal? I've never seen the remote gateway disagree with the checkout total like that.

If you use a different gateway, which may include "cheque", does that same problem happen? What about a non-UPS shipping?

**Comment by powerblue** [comment]
I'm only using PayPal and haven't tried any other payment processor, 
also I'm only using USPS and UPS, since these are all the most common 
and easiest to implement.

**Comment by powerblue** [comment]
I've just now installed the Table Rates shipping plugin: Version 1.6.0  
By WP Ronin, and the
Packages Configuration for WooCommerce is working perfectly when the 
Table Rate option is selected from the options presented by Packages 
Configuration for WooCommerce, however, anytime either the USPS or UPS 
option is selected that amount is doubled on the PayPal Order Summary.

**Comment by powerblue** [comment]
It seems like some code adds the USPS or UPS amount twice.

Thanks

**Comment by judgej** [comment]
You say your custom field is "_vendor". However, the WP GUI will not let you create a field starting with an underscore (since WP uses it in the background to indicate it is a custom field). The packages configuration screen also expects the custom field name to be entered without a prefixing underscore. Is this the case in your setup?

**Comment by judgej** [comment]
So the doubling up only happens with USPS and PayPal (or is that any payment gateway, e.g. try "check/cheque" as a very simple thing to try)? I don't have the USPS plugin, but would be happy to try it if you are happy to send it to me. jason@academe.co.uk

**Comment by powerblue** [comment]
The field in the GUI is actually, "Vendor", however, in the wp_postmeta 
it is actually _cpf_vendor.

**Comment by powerblue** [comment]
Here is the code establishing the Custom Field:

//Vendor field
     woocommerce_wp_text_input(
         array(
             'id'          => '_cpf_vendor',
             'label'       => __( 'Vendor', 'woocommerce' ),
             'desc_tip'    => 'true',
             //'type'        => 'text',
             'value'       =>  get_post_meta( $post->ID, '_cpf_vendor', 
true ),
             'description' => __( 'Enter the product Vendor here.', 
'woocommerce' )
         )
     );

**Comment by powerblue** [comment]
I've just set up the Check Payments option and tested it, and the total 
shipping amount is being doubled, the same way as with PayPal.

Thanks

**Comment by judgej** [comment]
Okay, so the payment method isn't the issue. Next, is it USPS? Does USPS double up the costs even when the packages plugin is not being used? What if you order three different products from three vendors - does it triple rather than double?

**Comment by powerblue** [comment]
Both UPS, and USPS work perfectly without doubling the shipping cost in 
the PayPal Order Summary when the packages plugin is not installed.

When there are 3 Test products used to test the packages plugin, the 
shipping cost is doubled in the PayPal order Summary.

Thanks

**Comment by powerblue** [comment]
*Three test product from 3 different Vendors.

**Comment by powerblue** [comment]
Here are the USPS and UPS plugins being used:

UPS (BASIC) WooCommerce Shipping
Version 1.1.4  By WooForce

USPS (BASIC) WooCommerce Shipping
Version 1.1.4  By WooForce

Thanks

**Comment by judgej** [comment]
That's all good stuff to know, and will help in solving the problem.

Attachments sent to github issues don't get attached to the issue, so you will need to send them to me directly. This is probably best anyway, if these are premium plugins. If they aren't premium, then a link would be fine, and my apologies for assuming they are.

**Comment by judgej** [comment]
Doh. I'll give it go:

https://en-gb.wordpress.org/plugins/ups-woocommerce-shipping-method/

**Comment by powerblue** [comment]
Hi,

They are the free plugins just search new plugins for USPS and UPS and 
there are right there.

Thanks

**Comment by powerblue** [comment]
Hi,

Does it look like the fix will be available very soon?

Thanks

**Comment by judgej** [comment]
I'm still trying to reproduce the problem - no luck yet.

**Comment by judgej** [comment]
I really cannot reproduce this doubling. What I see in PayPal is exactly what I see on the checkout screen, no matter what I do, for both UPS and USPS.

**Comment by powerblue** [comment]
What versions of wordpress and woocommerce are you using?

Thanks

**Comment by judgej** [comment]
WP 4.5.3
WC 2.6.2
UPS 1.1.4
USPS 1.1.4

**Comment by powerblue** [comment]
Are you using a live USPS account?

**Comment by judgej** [comment]
No I'm not. I'm just using the fallback price at the moment. TBH the need for an account is _very_ unclear, and trying to find out what type of account I need, how I can get a test account, and where to go for it, is just not obvious at all.

**Comment by powerblue** [comment]
Want to use my account?

**Comment by powerblue** [comment]
Hi,

Would you like to use my USPS credentials to test it?

Thanks

**Comment by judgej** [comment]
Sorry - been busy with many other things. If you would like to send me the details via https://onetimesecret.com/ (email me the link to the one-time secret details - **not** the credentials directly) then I'll give it a try.

jason@academe.co.uk

**Comment by powerblue** [comment]
Hi,

Here is what you need to test the USPS plugin:

--- snip ---

Thanks

**Comment by judgej** [comment]
Can confirm I'm got that (which means no-one else got it first).

**Comment by powerblue** [comment]
Hi,

Thanks, any knowledge on when a fix will be available?

Thanks

**Comment by judgej** [comment]
I've not seen any doubling with the USPS (Basic) shipping plugin. UPS seems to use different API keys, which I don't have, sop have not been able to test.

**Comment by powerblue** [comment]
You are using the credentials I sent?

**Comment by powerblue** [comment]
Hi,

I found the cause, which was another plugin that was installed:

VarkTech Min and Max Purchase for WooCommerce
Version 1.07.91 | By Vark

Packages for WooCommerce is working perfectly after deactivating this 
plugin.

Thanks

**Comment by judgej** [comment]
Glad it's all sorted.

**Comment by powerblue** [comment]
This packages plugin is very nice!
