### ISSUE TITLE
Publish to wordpress.org

### ISSUE THREAD

**Issue by judgej** [academe/wc-multiple-packages#3]

**Comment by judgej** [comment]
Names:

"WooCommerce Multiple Packages" is not allowed as it starts with "WooCommerce".

"Multiple Packages for WooCommerce" is already taken.

Trying "Packages Configuration for WooCommerce" which translates to slug "packages-configuration-for-woocommerce" and URL https://wordpress.org/plugins/packages-configuration-for-woocommerce/

**Comment by consilience** [comment]
Suggestions:

WooCommerce packages extended 
WooCommerce packages plus

**Comment by judgej** [comment]
Not allowed - they start with the name of another plugin.

> For example, if you have written an add-on plugin for WooCommerce, you may not name it "WooCommerce Improved Product Search" as that would generate the slug "woocommerce-improved-product-search" and that would conflict with the trademark of 'WooCommerce.' That said, it would be acceptable to submit the name "Woo Improved Product Search" which would use the slug "woo-improved-product-search" (woo not being trademarked you see).

**Comment by judgej** [comment]
I think it is clumsy attempt at the equivalent of a "vendor" name for plugins, but it only applies to trademarks. Though TBH I cannot see any evidence that it _is_ a registered trademark, though wordpress.org seem to claim it is.

**Comment by judgej** [comment]
Accepted name:

https://wordpress.org/plugins/packages-configuration-for-woocommerce/
